### ISSUE TITLE
Load ILDA file from URL instead of local file system

### ISSUE THREAD

**Issue by HankLloydRight** [possan/ilda.js#3]
Hello! 
  Fantastic library you have here, thank you!  
 I've been looking over the code, and I want to be able to trigger an ILDA preview by passing in a URL to an ILDA file.  The URL would return the raw binary data with MIME type "application/octet-stream".  Can you please suggest how to modify your code to take a URL instead?  
Many many thanks.

**Comment by rebane2001** [comment]
Generally for that you'd write a simple script that downloads the file to a temporary folder and then uses that on the original program

**Comment by HankLloydRight** [comment]
Thanks, but in this case the web server is running on an ESP32 and the user is using a browser.  I can't have a script download the file to the user's local machine (privacy and security concerns) and then turn around and upload it to this script running on an ESP32.  No, it would be much easier to just modify this script to accept a URL instead of a local file as the file source.  I tried several different ways but could not get it to work. I can have this script download the file from the URL (that's easy), but I can't get the raw data once downloaded into the byteArray format this script needs to process.

**Comment by HankLloydRight** [comment]
I found a great solution to this with this fantastic little library:  https://github.com/vobruba-martin/jquery.ajax.arraybuffer

Uses jquery/AJAX to load a URL into ArrayBuffer format.  Quick and easy.   Done.
